### ISSUE TITLE
CNY locale zh_Hans_CN is not recognised by Intl.NumberFormat

### ISSUE THREAD

**Issue by rishad-spenmo** [atnmorrison/country-locale-map#11]
it breaks the app when CNY locale is passed.

<img width="767" alt="Screenshot 2021-05-12 at 8 15 42 AM" src="https://user-images.githubusercontent.com/62295111/117910813-4094e500-b2fa-11eb-98ee-1fcf5f3281bf.png">

however, zh-CN works as intended. Any solutions?

**Comment by atnmorrison** [comment]
this should be fixed in the latest version zh-CN is the default for China
