### ISSUE TITLE
Kosovo is missing

### ISSUE THREAD

**Issue by osdiab** [atnmorrison/country-locale-map#23]
Found country code XK to be missing - might be due to its partial recognition though.

**Comment by atnmorrison** [comment]
Yeah, Canada recognizes it though and I'm Canadian so I'll add it :)

**Comment by juanpprieto** [comment]
Hey @atnmorrison,

Thanks for this great lib.

Did XK ever get added? — I'm not seeing it on ^1.8.0

Thanks!

**Comment by atnmorrison** [comment]
Hi all Kosovo has been added in 1.8.1
