### ISSUE TITLE
Netherlands Antilles (AN) missing

### ISSUE THREAD

**Issue by juanpprieto** [atnmorrison/country-locale-map#27]
Hi @atnmorrison,

It seems [AN](https://laendercode.net/en/2-letter-code/an#:~:text=AN%20is%20the%20two%2Dletter%20country%20abbreviation%20for%20Netherlands%20Antilles.) is  missing on ^1.8.0

Thanks for the lib!

JP

**Comment by atnmorrison** [comment]
Hi Juan,

I've added AN in version 1.8.1
