### ISSUE TITLE
Get Name by locale

### ISSUE THREAD

**Issue by fouille** [atnmorrison/country-locale-map#53]
Hello, 

It's possible to return name of country by locale, for exemple : 
```js
clm.getCountryNameByAlpha2("fr_FR"); // return French 
```

I didn't found in the documentation 

Thank's in advance

**Comment by MigFerreira** [comment]
Why not just do:
```js
clm.getCountryNameByAlpha2("fr_FR".split('_')[1]);
```

**Comment by fouille** [comment]
yes I did that, but for certain use cases it can be misleading. :-)

**Comment by atnmorrison** [comment]
Not every locale will have a country in it, some locale codes are just the language for example "en". I won't add it for now since there's a reasonable way to do it without adding to the code base. Thanks for the suggestion though!
