### ISSUE TITLE
Reduce bundle size during build time

### ISSUE THREAD

**Issue by bryanjtc** [atnmorrison/country-locale-map#54]
The main.js file imports two json files. They should be imported dynamically, so that when the condition is met only one is imported.
During the build process with webpack and rollup, both files are imported.

A recommended solution is this.
```ts
let countries;

if(typeof process !== 'undefined' && process && process.env && process.env.CLM_MODE == 'INTL') {
    import('./countries-intl.json').then(module => {
        countries = module.default;
    }).catch(error => {
        console.error("Error loading countries-intl.json:", error);
    });
} else {
    import('./countries.json').then(module => {
        countries = module.default;
    }).catch(error => {
        console.error("Error loading countries.json:", error);
    });
}
```
Both webpack and rollup should tree-shake the file that isn't use at build time.
Dynamic imports are only supported in esm files. This will be a breaking change.

Another solution would be adding new import paths for this package
```ts
import countryLocales from "country-locale-map/intl";
import countryLocales from "country-locale-map/default";
```
The require will be simple like this
`const countries = require('./countries.json'); `
or 
`const countries = require('./countries-intl.json');`

The common logic can be in a file called `common.js`
`index.js` imports a function from `common.js`. This function takes one parameter, the variable countries that still has the condition.
A new file intl.js for the intl json file and a new file default.js for the other json file.

The paths should be added to the exports field of the package.json

This will not be a breaking change. 
> Maybe the file and path should not be named default. Any other name will be fine.

Fuzzball is a big dependency. It has smaller versions that can be used instead.
See here: https://www.npmjs.com/package/fuzzball?activeTab=readme#lite-versions
The ultra lite version passes all the tests.

**Comment by atnmorrison** [comment]
Thanks for the suggestions, I'll likely go with the non breaking option but will take me a bit of time unless you want to do it and submit a PR :) , updating to fuzzball ultra lite was quick so I've done that as a patch 1.9.2

**Comment by atnmorrison** [comment]
adding to backlog and closing the issue
