### ISSUE TITLE
Currency for Chile is wrong

### ISSUE THREAD

**Issue by jCrip** [atnmorrison/country-locale-map#57]
Hi, 

I'm working on an app that handles currencies for a few Latin American
countries, and realized the currency code for Chile is wrong.

Unidad de Fomento (CLF) is a non-circulating currency for Chile, the Chilean peso is CLP.

The currency_name should be the Chilean peso also

Thanks

**Comment by atnmorrison** [comment]
Hey thanks for the fix, merged into latest version!
