### ISSUE TITLE
reformat locales

### ISSUE THREAD

**Issue by MigFerreira** [atnmorrison/country-locale-map#8]
For better compatibility with Javascript Intl I think locales should change from "_" to "-"
Example:
"en_CA" -> "en-CA"

**Comment by atnmorrison** [comment]
Yeah what I'll do is provide an option for which format to use and since it can be different systems use different formats and making the change would be a breaking change for some apps.

**Comment by atnmorrison** [comment]
In the latest version you can have locales returned in itnl friendly format by setting an environment variable in your project CLM_MODE='INTL'
