### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by schimini** [atnmorrison/country-locale-map#9]
I use this library in typescript project. 
If i submit type declarations to it would you consider adding them?

**Comment by atnmorrison** [comment]
sure if it'll help Typescript users without impacting JS users

**Comment by schimini** [comment]
Type declarations usually don't affect any users (besides adding more files to the library, in this case small files). Do you want me to post the file as a comment or to make a PR?

**Comment by atnmorrison** [comment]
PR would be great!

**Comment by schimini** [comment]
PR ready. Closing the issue. Thanks you for your response.
